version: 2
builds:
  - main: ./cmd/foolhtml
    binary: foolhtml
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
checksum:
  name_template: checksums.txt
archives:
  - formats: [binary]
snapshot:
  version_template: master
changelog:
  sort: asc
  filters:
    exclude:
      - "Merge pull request"
      - "Merge branch"
release:
  github:
    owner: wreulicke
    name: foolhtml
